version: '3'

networks:
  default:
    external:
      name: db_spring

services:
  db:
    image: mysql:8.0.18
    container_name: mysql-spring-boot
    ports:
      - 9999:3306
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=WALLET
  spring:
    container_name: spring-boot
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    networks:
      - default
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/WALLET?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root